"""empty message

Revision ID: 76c73cb2e63f
Revises: d5f946923e7f
Create Date: 2017-08-26 01:13:59.374775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c73cb2e63f'
down_revision = 'd5f946923e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('percentused', sa.Float(precision=4, asdecimal=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'percentused')
    # ### end Alembic commands ###
