"""empty message

Revision ID: d5f946923e7f
Revises: 
Create Date: 2017-08-25 22:14:46.808370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5f946923e7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('usagegb', sa.Integer(), nullable=True))
    op.add_column('User', sa.Column('usagemb', sa.Integer(), nullable=True))
    op.drop_column('User', 'usage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('usage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('User', 'usagemb')
    op.drop_column('User', 'usagegb')
    # ### end Alembic commands ###
